### ISSUE TITLE
HD and UHD video eye tracking dataset unavailable

### ISSUE THREAD

**Issue by FlyingFrank515** [UMass-LIDS/focas#1]
Hi 

I want to try the repo recently, but find that the inference dataset cannot be accessed now. Is there's another source to download it ? 
I would be appreciate if there's anyone can share it with me!!

**Comment by wld22145** [comment]
Hi Frank,

You can download our dataset archive using Dropbox with this link:
https://www.dropbox.com/s/f7gj0c5sxfe34ap/UD_UHD_EyeTracking_Videos.tar.gz?dl=0
I've also updated the README file.
